name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK with API key
        run: |
          flutter clean
          flutter build apk --release \
            --dart-define=GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}"
